"""
tests/phase2/test_domain.py
===========================
Phase 2 domain logic and business rule tests.

These tests validate aggregate replay, state transitions, domain invariants,
and command-handler orchestration using the in-memory event store.
"""
from __future__ import annotations

from datetime import datetime, timedelta
from decimal import Decimal

import pytest
import pytest_asyncio

from ledger.commands.handlers import (
    CreditAnalysisCompletedCommand,
    SubmitApplicationCommand,
    handle_credit_analysis_completed,
    handle_submit_application,
)
from ledger.domain.aggregates.agent_session import AgentSessionAggregate
from ledger.domain.aggregates.loan_application import (
    LoanApplicationAggregate,
    LoanApplicationState,
)
from ledger.domain.errors import DomainError
from ledger.event_store import InMemoryEventStore
from ledger.schema.events import (
    AgentType,
    AgentSessionStarted,
    ApplicationApproved,
    ApplicationSubmitted,
    CreditAnalysisCompleted,
    CreditAnalysisRequested,
    CreditDecision,
    DecisionGenerated,
    DecisionRequested,
    FraudScreeningRequested,
    LoanPurpose,
    PackageReadyForAnalysis,
    RiskTier,
)


@pytest_asyncio.fixture
async def store() -> InMemoryEventStore:
    return InMemoryEventStore()


def _submitted_event(application_id: str = "APEX-0001") -> dict:
    return ApplicationSubmitted(
        application_id=application_id,
        applicant_id="COMP-001",
        requested_amount_usd=Decimal("500000"),
        loan_purpose=LoanPurpose.WORKING_CAPITAL,
        loan_term_months=36,
        submission_channel="web",
        contact_email="borrower@example.com",
        contact_name="Borrower One",
        submitted_at=datetime.now(),
        application_reference=application_id,
    ).to_store_dict()


def _credit_requested_event(application_id: str = "APEX-0001") -> dict:
    return CreditAnalysisRequested(
        application_id=application_id,
        requested_at=datetime.now(),
        requested_by="system",
        priority="NORMAL",
    ).to_store_dict()


def _fraud_requested_event(application_id: str = "APEX-0001") -> dict:
    return FraudScreeningRequested(
        application_id=application_id,
        requested_at=datetime.now(),
        triggered_by_event_id="credit-event-001",
    ).to_store_dict()


def _decision_requested_event(application_id: str = "APEX-0001") -> dict:
    return DecisionRequested(
        application_id=application_id,
        requested_at=datetime.now(),
        all_analyses_complete=True,
        triggered_by_event_id="compliance-event-001",
    ).to_store_dict()


def _decision_generated_event(
    application_id: str = "APEX-0001",
    recommendation: str = "APPROVE",
    confidence: float = 0.82,
) -> dict:
    return DecisionGenerated(
        application_id=application_id,
        orchestrator_session_id="sess-orc-001",
        recommendation=recommendation,
        confidence=confidence,
        approved_amount_usd=Decimal("400000") if recommendation == "APPROVE" else None,
        conditions=["Monthly reporting"],
        executive_summary="Generated by orchestrator.",
        key_risks=[],
        contributing_sessions=["sess-crd-001", "sess-frd-001", "sess-cmp-001"],
        model_versions={"orchestrator": "claude-sonnet-4-20250514"},
        generated_at=datetime.now(),
    ).to_store_dict()


def _approved_event(application_id: str = "APEX-0001") -> dict:
    return ApplicationApproved(
        application_id=application_id,
        approved_amount_usd=Decimal("400000"),
        interest_rate_pct=7.25,
        term_months=36,
        conditions=["Monthly reporting"],
        approved_by="loan-officer-1",
        effective_date=datetime.now().date().isoformat(),
        approved_at=datetime.now(),
    ).to_store_dict()


def _credit_analysis_completed_event(application_id: str = "APEX-0001") -> dict:
    return CreditAnalysisCompleted(
        application_id=application_id,
        session_id="sess-crd-001",
        decision=CreditDecision(
            risk_tier=RiskTier.MEDIUM,
            recommended_limit_usd=Decimal("350000"),
            confidence=0.72,
            rationale="Healthy operating performance with manageable leverage.",
            key_concerns=[],
            data_quality_caveats=[],
            policy_overrides_applied=[],
        ),
        model_version="claude-sonnet-4-20250514",
        model_deployment_id="dep-credit-001",
        input_data_hash="hash-credit-001",
        analysis_duration_ms=1200,
        regulatory_basis=[],
        completed_at=datetime.now(),
    ).to_store_dict()


async def _append(store: InMemoryEventStore, stream_id: str, event: dict) -> None:
    version = await store.stream_version(stream_id)
    await store.append(stream_id, [event], expected_version=version)


@pytest.mark.asyncio
async def test_application_submitted_transitions_to_submitted(store: InMemoryEventStore):
    application_id = "APEX-SM-001"
    await store.append(f"loan-{application_id}", [_submitted_event(application_id)], expected_version=-1)

    app = await LoanApplicationAggregate.load(store, application_id)

    assert app.state == LoanApplicationState.SUBMITTED
    assert app.applicant_id == "COMP-001"


@pytest.mark.asyncio
async def test_out_of_order_approval_after_submission_raises_domain_error(store: InMemoryEventStore):
    application_id = "APEX-SM-002"
    await store.append(f"loan-{application_id}", [_submitted_event(application_id)], expected_version=-1)

    app = await LoanApplicationAggregate.load(store, application_id)

    with pytest.raises(DomainError):
        app._apply(_approved_event(application_id))


@pytest.mark.asyncio
async def test_application_approved_without_compliance_completion_raises(store: InMemoryEventStore):
    application_id = "APEX-BR-001"
    app = LoanApplicationAggregate(application_id=application_id)
    app._apply(_submitted_event(application_id))
    app._apply(_credit_requested_event(application_id))
    app._apply(_fraud_requested_event(application_id))
    app.state = LoanApplicationState.APPROVED_PENDING_HUMAN
    app.compliance_completed = False

    with pytest.raises(DomainError):
        app._apply(_approved_event(application_id))


@pytest.mark.asyncio
async def test_low_confidence_decision_forces_refer(store: InMemoryEventStore):
    application_id = "APEX-BR-002"
    app = LoanApplicationAggregate(application_id=application_id)
    app._apply(_submitted_event(application_id))
    app._apply(_credit_requested_event(application_id))
    app._apply(_fraud_requested_event(application_id))
    app._apply(
        {
            "event_type": "ComplianceCheckRequested",
            "event_version": 1,
            "payload": {
                "application_id": application_id,
                "requested_at": datetime.now().isoformat(),
                "triggered_by_event_id": "fraud-event-001",
                "regulation_set_version": "2026-Q1",
                "rules_to_evaluate": ["REG-001", "REG-002", "REG-003", "REG-004", "REG-005", "REG-006"],
            },
        }
    )
    app.mark_compliance_completed(False)
    app._apply(_decision_requested_event(application_id))

    app._apply(_decision_generated_event(application_id, recommendation="APPROVE", confidence=0.41))

    assert app.recommendation == "REFER"
    assert app.human_review_requested is True
    assert app.state == LoanApplicationState.PENDING_DECISION


@pytest.mark.asyncio
async def test_agent_session_requires_started_event_first(store: InMemoryEventStore):
    session_id = "sess-crd-missing-start"
    stream_id = f"agent-credit_analysis-{session_id}"
    await store.append(stream_id, [_credit_analysis_completed_event("APEX-GAS-001")], expected_version=-1)

    with pytest.raises(DomainError):
        await AgentSessionAggregate.load(store, "credit_analysis", session_id)


@pytest.mark.asyncio
async def test_handle_submit_application_writes_application_submitted(store: InMemoryEventStore):
    now = datetime.now()
    cmd = SubmitApplicationCommand(
        application_id="APEX-CMD-001",
        applicant_id="COMP-009",
        requested_amount_usd=Decimal("275000"),
        loan_purpose=LoanPurpose.WORKING_CAPITAL,
        loan_term_months=24,
        submission_channel="broker",
        contact_email="ops@example.com",
        contact_name="Ops User",
        submitted_at=now,
        application_reference="APEX-CMD-001",
        deadline=now + timedelta(days=7),
    )

    positions = await handle_submit_application(store, cmd)
    events = await store.load_stream("loan-APEX-CMD-001")

    assert positions == [0, 1]
    assert events[0]["event_type"] == "ApplicationSubmitted"
    assert events[0]["payload"]["application_id"] == "APEX-CMD-001"
    assert events[1]["event_type"] == "DocumentUploadRequested"


@pytest.mark.asyncio
async def test_handle_credit_analysis_completed_writes_fraud_screening_requested(store: InMemoryEventStore):
    application_id = "APEX-CMD-002"
    await store.append(f"loan-{application_id}", [_submitted_event(application_id)], expected_version=-1)
    await _append(store, f"loan-{application_id}", _credit_requested_event(application_id))
    await store.append(
        f"docpkg-{application_id}",
        [
            PackageReadyForAnalysis(
                package_id=application_id,
                application_id=application_id,
                documents_processed=3,
                has_quality_flags=False,
                quality_flag_count=0,
                ready_at=datetime.now(),
            ).to_store_dict()
        ],
        expected_version=-1,
    )

    cmd = CreditAnalysisCompletedCommand(
        application_id=application_id,
        triggered_by_event_id="credit-complete-001",
        requested_at=datetime.now(),
    )

    positions = await handle_credit_analysis_completed(store, cmd)
    events = await store.load_stream(f"loan-{application_id}")

    assert positions == [2]
    assert events[-1]["event_type"] == "FraudScreeningRequested"
    assert events[-1]["payload"]["triggered_by_event_id"] == "credit-complete-001"


@pytest.mark.asyncio
async def test_handle_credit_analysis_completed_validates_agent_session_and_tracing(store: InMemoryEventStore):
    application_id = "APEX-CMD-TRACE-001"
    session_id = "sess-credit-trace-001"
    await store.append(f"loan-{application_id}", [_submitted_event(application_id)], expected_version=-1)
    await _append(store, f"loan-{application_id}", _credit_requested_event(application_id))
    await store.append(
        f"docpkg-{application_id}",
        [
            PackageReadyForAnalysis(
                package_id=application_id,
                application_id=application_id,
                documents_processed=3,
                has_quality_flags=False,
                quality_flag_count=0,
                ready_at=datetime.now(),
            ).to_store_dict()
        ],
        expected_version=-1,
    )
    await store.append(
        f"agent-{AgentType.CREDIT_ANALYSIS.value}-{session_id}",
        [
            AgentSessionStarted(
                session_id=session_id,
                agent_type=AgentType.CREDIT_ANALYSIS,
                agent_id="credit-agent-1",
                application_id=application_id,
                model_version="claude-sonnet-4-20250514",
                langgraph_graph_version="graph-v1",
                context_source="loan-stream",
                context_token_count=256,
                started_at=datetime.now(),
            ).to_store_dict()
        ],
        expected_version=-1,
    )

    cmd = CreditAnalysisCompletedCommand(
        application_id=application_id,
        triggered_by_event_id="credit-complete-trace-001",
        requested_at=datetime.now(),
        session_id=session_id,
        model_version="claude-sonnet-4-20250514",
        correlation_id="corr-001",
        causation_id="cause-001",
    )

    await handle_credit_analysis_completed(store, cmd)
    events = await store.load_stream(f"loan-{application_id}")

    assert events[-1]["event_type"] == "FraudScreeningRequested"
    assert events[-1]["metadata"]["correlation_id"] == "corr-001"
    assert events[-1]["metadata"]["causation_id"] == "cause-001"